version: '3.3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD_HERE
      MYSQL_DATABASE: DATABASE_NAME_HERE
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - mysql_development

networks:
  mysql_development:
    driver: bridge
